Modified service bindings to add route bindings
cloudfoundry/cf_exporter pull request #127
Opened 2024-05-27 12:07 UTC by adamspd

2024-05-30 07:34 UTC, gmllt requested changes
I think fetch should go through its own fetch function `fetchServiceRouteBinding` in order to take maximum advantage of the parallelization offered by the worker system.

2024-05-30 07:34 UTC, gmllt commented on fetcher/fetcher_handlers.go
> +	routeBindings, _, _, err := session.V3().GetRouteBindings(LargeQuery)
I think fetch should go through its own fetch function `fetchServiceRouteBinding` in order to take maximum advantage of the parallelization offered by the worker system.

2024-05-30 15:38 UTC, gmllt commented
Sorry, I was so wrong when we discussed the usefulness of a new metric.
Now, I see the benefit to introduce a new metric only for service_route_bindings, as service instances bound to a route are not bound to any app at the same time.

You were right, it is better to introduce a new metric to avoid the emergence of service_bindings metric which would not contain an application_id

2024-06-18 08:08 UTC, gmllt approved these changes
LGTM, thanks @adamspd

2024-06-18 08:09 UTC, merged

2024-06-18 08:22 UTC, benjaminguttmann-avtq commented
like mentioned in the other PR please make sure to run the tests before a PR gets merged

https://github.com/cloudfoundry/cf_exporter/actions/runs/9561354046/job/26355377312

2024-06-18 08:31 UTC, adamspd commented
> like mentioned in the other PR please make sure to run the tests before a PR gets merged
> 
> https://github.com/cloudfoundry/cf_exporter/actions/runs/9561354046/job/26355377312

I should've put the PR in draft, I was about to add it just before the merge. Thanks for the reminder.